---

- name: Install cron
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: no
  with_items:
    - cron

- name: Ensure cron is set on boot time (EL6)
  service:
    name: cron
    enabled: yes
    state: started
